"""Testing module for api metadata. This is a test file designed to use pytest
and prepared with some basic assertions as base to add your own tests.

You can add new tests using the following structure:
```py
def test_{description for the test}(metadata):
    # Add your assertions inside the test function
    assert {statement_1 that returns true or false}
    assert {statement_2 that returns true or false}
```
The conftest.py module in the same directory includes the fixture to return
to your tests inside the argument variable `metadata` the value generated by
your function defined at `api.get_metadata`.

If your file grows in complexity, you can split it into multiple files in
the same folder. However, remember to add the prefix `test_` to the file.
"""
# pylint: disable=redefined-outer-name
# pylint: disable=unused-argument


def test_authors(metadata):
    """Tests that metadata provides authors information."""
    assert "author" in metadata
    assert metadata["author"] == ["Author Example"]


def test_emails(metadata):
    """Tests that metadata provides authors information."""
    assert "author-email" in metadata
    assert metadata["author-email"] == {"Author Example": "author@example.com"}


# def test_models(metadata):
#     """Tests that metadata provides models information."""
#     assert "something" in metadata
#     assert metadata["something"] == something
